---
title: "0_subset.Rmd"
author: "Henri Chung"
date: "8/4/2020"
output: html_document
---

```{r setup, include=FALSE}
## Section A: Set up libraries and load data
##################################################
list.of.packages <- c("tidyverse","tidymodels",  "reshape2", "furrr", "future", "doParallel", 
                      "text2vec", "stringi", "data.table", "janitor")#, "Rcpp", "profvis","Matrix", "themis", "stringi", "data.table", "tictoc")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages, repos = "https://cloud.r-project.org")
invisible(capture.output(lapply(list.of.packages, library, character.only = TRUE, warn.conflicts = FALSE, quietly = T)))

rm(list = ls()) #clear environment
source("code/nltksoil_functions.R") #Load functions
```



```{r}
#read in RDS data
otu_raw <- readRDS(paste(dataFolder, otuFilename_train, sep = ""))

#Save OTU and taxonomy data
otu_id <-  otu_raw %>%
  select(c("#OTU ID", "taxonomy")) %>%
  rename(otuid= `#OTU ID`)
saveRDS(otu_id, paste(dataFolder, "emp_deblur_90bp.qc_filtered_otu_taxonomy_list.RDS", sep = "/")) 

#read sample data, subset to soil
sampledata <- read.csv(paste(dataFolder, sampleFilename, sep = ""), sep = "\t") %>%
	janitor::clean_names()
colnames(sampledata) <- paste("metadata__", colnames(sampledata), sep = "")
```



```{r}
soil_sampledata <- sampledata  %>% 
  filter(grepl("soil", sampledata[["metadata__description"]]))

#get row indices of soil data
soil_ind <- colnames(otu_raw) %in% soil_sampledata[["metadata__x_sample_id"]]
#subset raw otu data by soil_ind and tranpose to sample = row, otu = columns
soil_raw <- otu_raw[,..soil_ind] %>% t()
#rename columns with OTU ID
colnames(soil_raw) <- otu_raw[["#OTU ID"]] #

#############################
#convert matrix soil_raw to dataframe to add columns
soil_raw <- as.data.frame(soil_raw)
#convert rownames to column
soil_raw[["metadata__x_sample_id"]] <- rownames(soil_raw)
```

```{r}

```

